apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-preprod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-preprod
  project: default
  source:
    path: .
    repoURL: https://github.com/mbrtsk/vcluster.git
    targetRevision: pre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  
